import { PhysicsEngine, fitCanvas, clearCanvas, themeColors, drawArrow, grid } from '../core/engine.js';
import { createLabShell, addRange, bindTransport, observeResize, format } from '../core/lab-ui.js';

export function createSimulator(container,{item,lowPerformance=false}){
 const ui=createLabShell(container,{equation:item.formula,explanation:`This first-milestone conceptual laboratory for ${item.title} provides responsive parameter exploration, vector overlays, a live graph, and equation substitution. Its architecture can be replaced later by a more specialised numerical model without changing navigation or storage.`,assumptions:['Educational model rather than a precision research solver','Dimensionless display scaling','Idealised boundary conditions'],metrics:[{key:'output',label:'Model output'},{key:'rate',label:'Rate'},{key:'phase',label:'Phase'},{key:'quality',label:'Solver'}]});
 const s={a:1,b:2,rate:1,t:0,speedScale:1,trail:[]};
 addRange(ui.controls,{key:'parameterA',label:'Primary parameter',min:.1,max:10,step:.1,value:s.a,unit:'',onInput:v=>s.a=v});addRange(ui.controls,{key:'parameterB',label:'Secondary parameter',min:.1,max:10,step:.1,value:s.b,unit:'',onInput:v=>s.b=v});addRange(ui.controls,{key:'rate',label:'Evolution rate',min:.1,max:4,step:.1,value:s.rate,unit:'×',onInput:v=>s.rate=v});
 const resizeOff=observeResize(ui.canvas.parentElement,()=>render());const reset=()=>{s.t=0;s.trail=[];};const engine=new PhysicsEngine({targetFps:lowPerformance?30:60,fixedDt:1/120,update(dt){s.t+=dt*s.speedScale*s.rate;const out=s.a*Math.sin(s.t)+s.b*Math.cos(s.t*.67);s.trail.push(out);if(s.trail.length>(lowPerformance?80:220))s.trail.shift();},render});
 function render(){const{ctx,width,height}=fitCanvas(ui.canvas,lowPerformance?1:1.75);const c=themeColors();clearCanvas(ctx,width,height);grid(ctx,width,height,lowPerformance?85:50);const cx=width*.38,cy=height*.44,r=Math.min(width,height)*.18;ctx.strokeStyle=c.border;ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();const angle=s.t;const x=cx+r*Math.cos(angle),y=cy+r*Math.sin(angle);ctx.fillStyle=c.accent;ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fill();drawArrow(ctx,cx,cy,x,y,c.accent3,'state');drawArrow(ctx,x,y,x-r*.45*Math.sin(angle),y+r*.45*Math.cos(angle),c.warning,'rate');const gx=width*.58,gy=height*.2,gw=Math.max(100,width*.34),gh=height*.5;ctx.strokeStyle=c.border;ctx.strokeRect(gx,gy,gw,gh);ctx.strokeStyle=c.accent2;ctx.lineWidth=2;ctx.beginPath();const max=Math.max(1,...s.trail.map(Math.abs));s.trail.forEach((v,i)=>{const px=gx+i/Math.max(1,s.trail.length-1)*gw,py=gy+gh/2-v/max*gh*.42;i?ctx.lineTo(px,py):ctx.moveTo(px,py);});ctx.stroke();const out=s.a*Math.sin(s.t)+s.b*Math.cos(s.t*.67);ui.metric('output',format(out));ui.metric('rate',`${format(s.rate)}×`);ui.metric('phase',`${format((s.t%(Math.PI*2))*180/Math.PI)}°`);ui.metric('quality',lowPerformance?'30 FPS':'60 FPS');ui.readout.textContent=`${item.category} model · output=${format(out)}`;ui.setEquation(`${item.formula}  |  substituted model output = ${format(out)}`);}
 bindTransport(ui,engine,reset,v=>s.speedScale=v);engine.start();return()=>{engine.destroy();resizeOff();};
}
