import { PhysicsEngine, fitCanvas, clearCanvas, themeColors, drawArrow, grid } from '../core/engine.js';
import { createLabShell, addRange, bindTransport, observeResize, format } from '../core/lab-ui.js';

export function createSimulator(container,{item,lowPerformance=false}){
 const isCharge=item.number<=63; const isParallel=item.title.includes('Parallel'); const isSeries=item.title.includes('Series'); const isRC=item.title.includes('Capacitor')||item.title.includes('RC');
 const ui=createLabShell(container,{equation:item.formula,explanation:isCharge?'Move between electrostatic quantities and inspect the inverse-square dependence.':'Adjust source and component values while the schematic and numerical readouts update immediately.',assumptions:['Ideal components','Negligible wire resistance','Point charges for electrostatic models'],metrics:[{key:'current',label:isCharge?'Force':'Current'},{key:'power',label:isCharge?'Field':'Power'},{key:'req',label:isCharge?'Potential':'Equivalent R'},{key:'tau',label:'Time constant'}]});
 const s={V:12,R1:20,R2:30,q1:2,q2:-3,r:.5,C:.01,t:0,speedScale:1};
 if(isCharge){addRange(ui.controls,{key:'q1',label:'Charge q₁',min:-10,max:10,step:.5,value:s.q1,unit:' μC',onInput:v=>s.q1=v});addRange(ui.controls,{key:'q2',label:'Charge q₂',min:-10,max:10,step:.5,value:s.q2,unit:' μC',onInput:v=>s.q2=v});addRange(ui.controls,{key:'distance',label:'Separation',min:.1,max:2,step:.05,value:s.r,unit:' m',onInput:v=>s.r=v});}
 else{addRange(ui.controls,{key:'voltage',label:'Source voltage',min:1,max:48,step:.5,value:s.V,unit:' V',onInput:v=>s.V=v});addRange(ui.controls,{key:'r1',label:'Resistance R₁',min:1,max:200,step:1,value:s.R1,unit:' Ω',onInput:v=>s.R1=v});if(isSeries||isParallel||item.title.includes('Kirchhoff')||item.title.includes('Wheatstone'))addRange(ui.controls,{key:'r2',label:'Resistance R₂',min:1,max:200,step:1,value:s.R2,unit:' Ω',onInput:v=>s.R2=v});if(isRC)addRange(ui.controls,{key:'capacitance',label:'Capacitance',min:.001,max:.1,step:.001,value:s.C,unit:' F',onInput:v=>{s.C=v;s.t=0;}});}
 const resizeOff=observeResize(ui.canvas.parentElement,()=>render());const reset=()=>s.t=0;const engine=new PhysicsEngine({targetFps:lowPerformance?30:60,fixedDt:1/120,update(dt){s.t+=dt*s.speedScale;},render});
 function render(){const{ctx,width,height}=fitCanvas(ui.canvas,lowPerformance?1:1.75);const c=themeColors();clearCanvas(ctx,width,height);grid(ctx,width,height,lowPerformance?85:50);
 let current=0,power=0,req=s.R1,tau=s.R1*s.C;
 if(isCharge){const k=8.9875517923e9,q1=s.q1*1e-6,q2=s.q2*1e-6;const F=k*q1*q2/s.r**2,E=k*q1/s.r**2,Vp=k*q1/s.r;const y=height*.5,x1=width*.32,x2=width*.68;ctx.fillStyle=s.q1>=0?c.danger:c.accent;ctx.beginPath();ctx.arc(x1,y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle=s.q2>=0?c.danger:c.accent;ctx.beginPath();ctx.arc(x2,y,28,0,Math.PI*2);ctx.fill();ctx.fillStyle=c.text;ctx.font='700 13px ui-monospace,monospace';ctx.fillText(`${format(s.q1)} μC`,x1-23,y+5);ctx.fillText(`${format(s.q2)} μC`,x2-23,y+5);drawArrow(ctx,x1+35,y,x2-35,y,F>=0?c.danger:c.accent3,F>=0?'repel':'attract');current=F;power=E;req=Vp;ui.setEquation(`F=kq₁q₂/r²=${format(F,4)} N`);
 }else{req=isSeries?s.R1+s.R2:isParallel?1/(1/s.R1+1/s.R2):s.R1;current=s.V/req;power=s.V*current;const left=70,right=width-70,top=height*.30,bottom=height*.70;ctx.strokeStyle=c.text;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(left,top);ctx.lineTo(right,top);ctx.lineTo(right,bottom);ctx.lineTo(left,bottom);ctx.closePath();ctx.stroke();ctx.strokeStyle=c.accent;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(left-7,(top+bottom)/2-25);ctx.lineTo(left-7,(top+bottom)/2+25);ctx.moveTo(left+7,(top+bottom)/2-14);ctx.lineTo(left+7,(top+bottom)/2+14);ctx.stroke();const drawRes=(x,y,w)=>{ctx.strokeStyle=c.warning;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-w/2,y);for(let i=0;i<8;i++)ctx.lineTo(x-w/2+(i+.5)*w/8,y+(i%2?-12:12));ctx.lineTo(x+w/2,y);ctx.stroke();};drawRes(width*.5,top,width*.3);if(isParallel)drawRes(width*.5,bottom,width*.3);const phase=(s.t*current*25)%1;ctx.fillStyle=c.accent3;for(let i=0;i<8;i++){const p=(i/8+phase)%1;let x,y;if(p<.25){x=left+(right-left)*p/.25;y=top}else if(p<.5){x=right;y=top+(bottom-top)*(p-.25)/.25}else if(p<.75){x=right-(right-left)*(p-.5)/.25;y=bottom}else{x=left;y=bottom-(bottom-top)*(p-.75)/.25}ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();}
 ui.setEquation(isRC?`τ=RC=${format(tau)} s;  V_C=${format(s.V*(1-Math.exp(-s.t/tau)))} V`:`I=V/R=${format(s.V)}/${format(req)}=${format(current)} A`);}
 ui.metric('current',isCharge?`${format(current,4)} N`:`${format(current)} A`);ui.metric('power',isCharge?`${format(power)} N/C`:`${format(power)} W`);ui.metric('req',isCharge?`${format(req)} V`:`${format(req)} Ω`);ui.metric('tau',isRC?`${format(tau)} s`:'—');ui.readout.textContent=isCharge?`r=${format(s.r)} m · F=${format(current,4)} N`:`V=${format(s.V)} V · I=${format(current)} A`;}
 bindTransport(ui,engine,reset,v=>s.speedScale=v);engine.start();return()=>{engine.destroy();resizeOff();};
}
