import { PhysicsEngine, fitCanvas, clearCanvas, themeColors, grid } from '../core/engine.js';
import { createLabShell, addRange, bindTransport, observeResize, format } from '../core/lab-ui.js';

export function createSimulator(container,{item,lowPerformance=false}){
 const mirror=item.title.includes('Mirror'); const interference=item.title.includes('slit')||item.title.includes('grating')||item.title.includes('Diffraction');
 const ui=createLabShell(container,{equation:item.formula,explanation:interference?'Wave-optics controls change fringe spacing and the intensity pattern on the screen.':'Principal rays are traced using the thin-element approximation. Drag-free controls keep the model reliable on touch devices.',assumptions:['Paraxial rays','Thin lens or spherical mirror approximation','Monochromatic light unless dispersion is selected'],metrics:[{key:'image',label:interference?'Fringe spacing':'Image distance'},{key:'mag',label:'Magnification'},{key:'type',label:'Image type'},{key:'focus',label:'Focal length'}]});
 const s={f:12,u:26,h:5,lambda:550,d:.25,D:2,t:0,speedScale:1};
 if(interference){addRange(ui.controls,{key:'lambda',label:'Wavelength',min:380,max:700,step:5,value:s.lambda,unit:' nm',onInput:v=>s.lambda=v});addRange(ui.controls,{key:'slit',label:'Slit separation',min:.05,max:1,step:.01,value:s.d,unit:' mm',onInput:v=>s.d=v});addRange(ui.controls,{key:'screen',label:'Screen distance',min:.5,max:5,step:.1,value:s.D,unit:' m',onInput:v=>s.D=v});}
 else{addRange(ui.controls,{key:'focus',label:'Focal length',min:-30,max:30,step:1,value:s.f,unit:' cm',onInput:v=>s.f=Math.abs(v)<1?(v<0?-1:1):v});addRange(ui.controls,{key:'object',label:'Object distance',min:3,max:60,step:1,value:s.u,unit:' cm',onInput:v=>s.u=v});addRange(ui.controls,{key:'height',label:'Object height',min:1,max:12,step:.5,value:s.h,unit:' cm',onInput:v=>s.h=v});}
 const resizeOff=observeResize(ui.canvas.parentElement,()=>render());const reset=()=>s.t=0;const engine=new PhysicsEngine({targetFps:lowPerformance?30:60,fixedDt:1/60,update(dt){s.t+=dt*s.speedScale;},render});
 function render(){const{ctx,width,height}=fitCanvas(ui.canvas,lowPerformance?1:1.75);const c=themeColors();clearCanvas(ctx,width,height);grid(ctx,width,height,lowPerformance?85:50);const axis=height*.52;ctx.strokeStyle=c.border;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(20,axis);ctx.lineTo(width-20,axis);ctx.stroke();
 if(interference){const beta=(s.lambda*1e-9*s.D)/(s.d*1e-3);const center=width*.72;ctx.fillStyle=c.muted;ctx.fillRect(center-2,40,4,height-80);const maxY=height*.4;for(let y=-maxY;y<=maxY;y+=2){const physical=y/maxY*beta*8;const phase=Math.PI*physical/beta;const intensity=Math.cos(phase)**2;ctx.fillStyle=`rgba(103,232,249,${.04+.8*intensity})`;ctx.fillRect(center+5,axis+y,Math.max(2,intensity*(width-center-25)),2);}ctx.fillStyle=c.accent;ctx.beginPath();ctx.arc(width*.18,axis,9,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c.accent2;ctx.beginPath();ctx.moveTo(width*.2,axis);ctx.lineTo(center,axis-height*.18);ctx.moveTo(width*.2,axis);ctx.lineTo(center,axis+height*.18);ctx.stroke();ui.metric('image',`${format(beta*1000,3)} mm`);ui.metric('mag','—');ui.metric('type','Interference');ui.metric('focus','—');ui.setEquation(`β=λD/d=${format(beta*1000,3)} mm`);ui.readout.textContent=`λ=${format(s.lambda)} nm · fringe=${format(beta*1000,3)} mm`;
 }else{const elementX=width*.56,scale=Math.min(8,(width*.45)/65);const objectX=elementX-s.u*scale;const denom=1/s.f-1/s.u;const v=Math.abs(denom)<1e-6?1e6:1/denom;const imageX=elementX+v*scale;const m=-v/s.u;const objH=s.h*scale*2,imgH=m*objH;ctx.strokeStyle=c.accent;ctx.lineWidth=4;ctx.beginPath();if(mirror){ctx.arc(elementX+30,axis,Math.max(25,Math.abs(s.f)*scale*2),Math.PI*.65,Math.PI*1.35);}else{ctx.moveTo(elementX,50);ctx.quadraticCurveTo(elementX+(s.f>0?18:-18),axis,elementX,height-50);}ctx.stroke();const arrow=(x,h,color)=>{ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,axis);ctx.lineTo(x,axis-h);ctx.stroke();ctx.beginPath();ctx.moveTo(x,axis-h);ctx.lineTo(x-7,axis-h+13);ctx.lineTo(x+7,axis-h+13);ctx.closePath();ctx.fill();};arrow(objectX,objH,c.accent3);if(Math.abs(imageX)<width*3)arrow(imageX,imgH,c.warning);const topObj={x:objectX,y:axis-objH};ctx.strokeStyle=c.accent2;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(topObj.x,topObj.y);ctx.lineTo(elementX,topObj.y);ctx.lineTo(imageX,axis-imgH);ctx.stroke();ctx.strokeStyle=c.danger;ctx.beginPath();ctx.moveTo(topObj.x,topObj.y);ctx.lineTo(elementX,axis);ctx.lineTo(imageX,axis-imgH);ctx.stroke();const type=v>0?'Real':'Virtual';ui.metric('image',`${format(v)} cm`);ui.metric('mag',`${format(m)}×`);ui.metric('type',type);ui.metric('focus',`${format(s.f)} cm`);ui.setEquation(`1/f=1/v+1/u  →  v=${format(v)} cm,  m=${format(m)}`);ui.readout.textContent=`u=${format(s.u)} cm · v=${format(v)} cm · ${type}`;}
 }
 bindTransport(ui,engine,reset,v=>s.speedScale=v);engine.start();return()=>{engine.destroy();resizeOff();};
}
